### ISSUE TITLE
共享

### ISSUE THREAD

**Issue by zeal-up** [cy69855522/AI-Paper-Drawer#1]
我看这个repo好像star的人比较少，但是qq群人倒是不少。我自己做了一个repo记录了一点论文，针对一些论文给了一些概括，如果需要的话我可以做一个中文的出来，或者如果您的团队有需要，我可以提供一些工作，我对图网络挺感兴趣的。以下是我的repo链接：
https://github.com/zeal-github/Graph-neural-network

**Comment by cy69855522** [comment]
感谢分享！这个repo和群都是刚建的，Github主要是希望记录大家的学习成果，做一个整合，一方面方便复习，另一方面，聚集大家的成果帮助非英文母语的学者加速熟悉领域，更好地理解图网络。目前这个项目没什么内容，还需要更多的努力才能变得更好，如果可以，十分欢迎分享有关图网络的中文资料，期待您的大作。我先把您的项目链接收录其中了org。

**Comment by darrenzhang1007** [comment]
清华的周杰教授，发表了那篇图论文的综述，而且也在GitHub上发布了一个必看的GitHub列表，链接如下：
https://github.com/thunlp/GNNPapers

**Comment by cy69855522** [comment]
> 清华的周杰教授，发表了那篇图论文的综述，而且也在GitHub上发布了一个必看的GitHub列表，链接如下：
> https://github.com/thunlp/GNNPapers

谢谢分享，已添加至相关资料
